#!/bin/bash
if [ "$2" == ""  ] 
then
    touch $1.h $1.cpp
elif [ "$3" == "" ] 
then
    touch $2/$1.h $1.cpp
elif [ "$2" == "-1" ] && [ "$3" == "-1" ] 
then
    touch src/$1.h include/$1.cpp
else
    touch $1.h $1.cpp
fi
